# Generated by Django 5.0.2 on 2024-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_school_department_unit_rename_unit_staff_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[('ACADEMIC', 'T'), ('NON_ACADEMIC', 'NT')], default='ACADEMIC', max_length=20),
        ),
    ]
