# Generated by Django 5.0.2 on 2024-02-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_staff_gender_alter_staff_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.CharField(max_length=100)),
                ('done_on', models.DateField()),
                ('authorized_by', models.CharField(max_length=100)),
                ('authorized_signature', models.CharField(max_length=100)),
                ('acknowledged_by_hr', models.CharField(max_length=100)),
                ('visa_for_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_means', models.CharField(choices=[('PROVIDED', 'Provided'), ('PERSONAL', 'Personal'), ('PUBLIC', 'Public')], max_length=100)),
                ('vehicle_identification', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_manager', to='core.staff'),
        ),
        migrations.CreateModel(
            name='MissionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('STAFF', 'Staff'), ('TUTORIAL_ASSISTANT', 'Tutorial Assistant'), ('ASSISTANT_LECTURER', 'Assistant Lecturer'), ('LECTURER', 'Lecturer'), ('SENIOR_LECTURER', 'Senior Lecturer'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('PROFESSOR', 'Professor')], max_length=100)),
                ('purpose_of_mission', models.TextField()),
                ('expected_results', models.TextField()),
                ('destination', models.CharField(choices=[('KIGALI', 'Kigali'), ('HUYE', 'Huye'), ('MUSANZE', 'Musanze'), ('RUBAVU', 'Rubavu'), ('NYAGATARE', 'Nyagatare'), ('RUSIZI', 'Rusizi'), ('KARONGI', 'Karongi'), ('NYANZA', 'Nyanza'), ('GAKENKE', 'Gakenke'), ('NGORORERO', 'Ngororero'), ('KAMONYI', 'Kamonyi'), ('RULINDO', 'Rulindo'), ('BUGESERA', 'Bugesera'), ('NYAMASHEKE', 'Nyamasheke'), ('NYARUGURU', 'Nyaruguru'), ('GICUMBI', 'Gicumbi'), ('KIREHE', 'Kirehe'), ('RWAMAGANA', 'Rwamagana'), ('KAYONZA', 'Kayonza'), ('GATSIBO', 'Gatsibo')], max_length=100)),
                ('distance_km', models.IntegerField(blank=True, null=True)),
                ('departure_date', models.DateField()),
                ('returning_date', models.DateField()),
                ('duration_days', models.IntegerField(editable=False)),
                ('duration_nights', models.IntegerField(editable=False)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_signature', models.CharField(max_length=100)),
                ('approval_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.approvaldetails')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_orders', to='core.staff')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
                ('transportation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
                ('mission_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.missionorder')),
            ],
        ),
    ]
