# Generated by Django 5.0.2 on 2024-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_approvaldetails_transportation_unit_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionorder',
            name='destination',
            field=models.CharField(choices=[('KIGALI', 'Kigali'), ('HUYE', 'Huye'), ('MUSANZE', 'Musanze'), ('RUBAVU', 'Rubavu'), ('NYAGATARE', 'Nyagatare'), ('RUSIZI', 'Rusizi'), ('KARONGI', 'Karongi'), ('NYANZA', 'Nyanza'), ('GAKENKE', 'Gakenke'), ('NGORORERO', 'Ngororero'), ('KAMONYI', 'Kamonyi'), ('RULINDO', 'Rulindo'), ('BUGESERA', 'Bugesera'), ('NYAMASHEKE', 'Nyamasheke'), ('NYARUGURU', 'Nyaruguru'), ('GICUMBI', 'Gicumbi'), ('KIREHE', 'Kirehe'), ('RWAMAGANA', 'Rwamagana'), ('KAYONZA', 'Kayonza'), ('GATSIBO', 'Gatsibo'), ('NGOMA', 'Ngoma'), ('BURERA', 'Burera'), ('NYAMAGABE', 'Nyamagabe'), ('RUHAANGO', 'Ruhaango'), ('RUTSIRO', 'Rutsiro')], max_length=100),
        ),
    ]
