# Generated by Django 5.0.2 on 2024-02-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_issued_to_missionorder_staff_approval_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionAttachments',
            new_name='MissionAttachment',
        ),
        migrations.RenameField(
            model_name='missionorder',
            old_name='Role',
            new_name='role',
        ),
    ]
