# Generated by Django 5.0.2 on 2024-02-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_campus_college_unit_staff_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='college',
        ),
        migrations.RemoveField(
            model_name='department',
            name='school',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
